name: Build site
on:
  pull_request:
    branches: ["main"]
jobs:
  build-pelican:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
        with:
      - uses: apache/infrastructure-actions/pelican@main
        with:
          publish: false
