# The workflow deletes staging branches after 21 days of inactivity

name: Delete Stale Branches

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  delete-stale-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install PyGithub

      - name: Delete stale branches
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python <<EOF
          from datetime import datetime, timedelta
          from github import Github

          # Authenticate with the GitHub API
          g = Github("${{ secrets.GITHUB_TOKEN }}")

          # Get the repository
          repo = g.get_repo("${{ github.repository }}")

          # Define the inactivity period
          inactivity_period = timedelta(days=21)

          # Get current time
          now = datetime.utcnow()

          # Iterate through branches
          for branch in repo.get_branches():
              if branch.name.startswith("-staging"):
                  # Get the last commit
                  commit = repo.get_commit(branch.commit.sha)
                  last_activity = commit.commit.author.date

                  # Check if the branch is inactive
                  if now - last_activity > inactivity_period:
                      print(f"Deleting branch: {branch.name}")
                      try:
                          repo.get_git_ref(f"heads/{branch.name}").delete()
                      except Exception as e:
                          print(f"Failed to delete branch {branch.name}: {e}")
          EOF
