# This workflow will create a staged version of the website. The last branch for which this workflow
# was run will be published to https://datafusion.staged.apache.org/
# To enable this work flow, you simply need a PR that has a branch name that begins with `site/`
# and targets `main`. This workflow will build the site and push the results into the branch
# `asf-staging`. From there, the ASF infrastructure will identify that a stage site has been
# built and will publish to the link above.

name: Stage Site
on:
  pull_request:
    branches: ["main"]
jobs:
  build-pelican:
    if: startsWith(github.head_ref, 'site/')
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: apache/infrastructure-actions/pelican@main
        with:
          destination: 'asf-staging'
          gfm: 'false'
          output: 'blog'
