# This workflow ensures that any PR targeted at main will build properly.
# A failure in this workflow should prevent any merging into main.
name: Build site
on:
  pull_request:
    branches: ["main"]
jobs:
  build-pelican:
    if: startsWith(github.head_ref, 'site/')
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'main'
      - uses: apache/infrastructure-actions/pelican@main
        with:
          destination: "${{ github.head_ref }}-staging"
          gfm: 'false'
